### ISSUE TITLE
Datenbankabfragen, Filter

### ISSUE THREAD

**Issue by claudehohl** [claudehohl/engelsystem#10]

**Comment by claudehohl** [comment]
Works for me, finally. The "UNION doesn't work"-bug was almost a showstopper... (https://github.com/agershun/alasql/issues/485)

**Comment by fuserMRX** [comment]
Hi @claudehohl , could you please elaborate a bit. So now `UNION` and `UNION ALL` work properly? because I still face similiar issue described in https://stackoverflow.com/questions/35894671/alasql-union-or-union-all-only-gives-results-from-table
